# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20171022_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.DeleteModel(
            name='ProjectSolution',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
