# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='due',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
